### ISSUE TITLE
[Feature] Redesigning Offer

### ISSUE THREAD

**Issue by ravimahfunda** [buahbatu/satu-tanya#14]
Hey, I've been following your project since last week
and to be honest, I'm impressed.

Now I'm offering some redesign to match your brand logo and your brand.
And maybe I can help you to make the store listing images.

In this design, I'm using [Nunito Font](https://fonts.google.com/specimen/Nunito) and the icon set I'm using [Feather Icons](https://feathericons.com/). If you're using flutter, you can use [this](https://pub.dev/packages/feather_icons_flutter).

Go take a look!!

![Group (7)](https://user-images.githubusercontent.com/23191531/65372213-4b1ee880-dc97-11e9-82bb-adf133c1edf1.png)

![Group 2](https://user-images.githubusercontent.com/23191531/65372207-2dea1a00-dc97-11e9-98eb-1f29048c6998.png)

![Group 2 1](https://user-images.githubusercontent.com/23191531/65372203-17dc5980-dc97-11e9-99fd-e6d29f832dfa.png)

**Comment by alifgiant** [comment]
nicely done. thanks. will code this soon

**Comment by ravimahfunda** [comment]
im looking forward to it

**Comment by alifgiant** [comment]
implement new colour theme, but did not implement new icons, bottom nav and sheet.
