### ISSUE TITLE
[Featured] Pop Quiz

### ISSUE THREAD

**Issue by kiritogit-design** [buahbatu/satu-tanya#26]
contoh pop quiz bisa kyak gini
https://www.idntimes.com/life/relationship/stella/tipe-single-seperti-apa-kamu-quiz

**Comment by alifgiant** [comment]
hmm, pop up yang cuma ya, ga dan mungkin ga rame.
sepertinya ga akan meningkatkan interaction time, sedangkan effort code tinggi
